export const TABLES = {
  COUNTRY: 'country',
  SHOP: 'shops',
  RESTURANT: 'resturants',
  POLICY: 'policies',
  SHOP_PAYMENT_METHOD: 'shop_payment_method',
  SHOP_CATEGORIES: 'shop_categories',
  ADMIN: 'admins',
  CATEGORIES: 'categories',
  CUSTOMER: 'customers',
  PRODUCT: 'products',
  RATING: 'ratings',
  ORDER: 'orders',
  ORDER_STATUS: 'order_status',
  PAYMENT_METHOD: 'payment_methods',
  PRODUCT_IMAGES: 'product_images',
  PRICING_PLANS: 'pricing_plans',
  SHOP_RECHARGE_LOGS: 'shop_recharge_logs',
  DELIVERY_OPTIONS: 'delivery_options',
  SHOP_DELIVERY_OPTIONS: 'shop_delivery_options',
  CONTACT_US: 'contact_us',
  SHIPPING_ADDRESS: 'shipping_address',
  DISCOUNT_CODE: 'discount_codes',
  OPERATING_SCHEDULES: 'operating_schedules',
} as const
